### ISSUE TITLE
video importing

### ISSUE THREAD

**Issue by alireza-rezaeifard** [mtkarimi/persian-license-plate-recognition#10]
I import a video to the project to check the license plates in the video, the license plates are recognized in the image, but they are not shown and saved in the software.

**Comment by mh-ahmadii** [comment]
Hi,
I have a question. I ran the 'best.pt' model using YOLOv5, and in my experience, it was very slow, and the detection quality was very poor. So, I don't know how to run this code. Is it possible for you to share your Python version and also the version of requirements with me (or any other necessary components) to run this code? I can't run this code on my PC (it's doesn't have a GPU), and when I run it on my laptop (with a 4GB GPU), it runs, but none of the buttons or other functions work.

I'm not sure what I should do.

**Comment by mh-ahmadii** [comment]
for me it stuck on the 'Adding AutoShape', this is the CMD log:



E:\Development\ML\smart-resident-guard>python home-yolo.py
YOLOv5  2024-3-3 Python-3.9.0 torch-2.2.0+cpu CPU

Fusing layers...
YOLOv5s summary: 157 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
Adding AutoShape...
YOLOv5  2024-3-3 Python-3.9.0 torch-2.2.0+cpu CPU

Fusing layers...
Model summary: 224 layers, 7167184 parameters, 0 gradients
Adding AutoShape...

**Comment by alireza-rezaeifard** [comment]
> for me it stuck on the 'Adding AutoShape', this is the CMD log:
> 
> 
> 
> E:\Development\ML\smart-resident-guard>python home-yolo.py
> YOLOv5  2024-3-3 Python-3.9.0 torch-2.2.0+cpu CPU
> 
> Fusing layers...
> YOLOv5s summary: 157 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
> Adding AutoShape...
> YOLOv5  2024-3-3 Python-3.9.0 torch-2.2.0+cpu CPU
> 
> Fusing layers...
> Model summary: 224 layers, 7167184 parameters, 0 gradients
> Adding AutoShape...

for me is the same this error force me to install linux ubounto and i run it on ubounto
but still not working properly

**Comment by mtkarimi** [comment]
i updated to core, please clone and let me know
if the performance is not good enough please consider the hardware requirements

**Comment by mh-ahmadii** [comment]
> i updated to core, please clone and let me know if the performance is not good enough please consider the hardware requirements

Thank you so much! It's now working correctly for me.

However, I have another question. I ran this on my laptop, which has a Core i5 6th Gen CPU with 16 GB of RAM and 4 GB of graphics memory (Radeon 530 GDDR3). Despite this, I'm only getting 1, maximum 2 frames per second (FPS), and it's running too slowly, even when I change the source to video file. So do you think the issue is with my system configuration, or could it be related to other factors?

**Comment by alireza-rezaeifard** [comment]
thank you for reply 
my hardware is :
cpu : intel core i5-12400f
gpu : rtx 3060 dual
ram : 2*8gb corssair 3200

i think it's ok to run this app
