### ISSUE TITLE
Runing python home-yolo.py

### ISSUE THREAD

**Issue by mohsenkondori** [mtkarimi/persian-license-plate-recognition#16]
Hi there,

I'm writing to report an issue with the home-yolo.py script. I started it approximately 7 hours ago, but it appears to be stuck and hasn't made any progress.

Current CPU usage for the script is around 10%.

Could you please advise on how to troubleshoot this issue or suggest a potential fix?
@mtkarimi @mohammadhssn 

![image](https://github.com/mtkarimi/persian-license-plate-recognition/assets/50166193/e84d0d65-1847-4b41-a755-8cb58cdf9ff0)

After restart the python home-yolo.py command:

![image](https://github.com/mtkarimi/persian-license-plate-recognition/assets/50166193/9c10d13c-0a7e-4f01-abf3-7bfd50cf4085)

And I ran with qt:
![image](https://github.com/mtkarimi/persian-license-plate-recognition/assets/50166193/bcca3591-b918-4292-8b9d-a63975988d38)

**Comment by mtkarimi** [comment]
Hmmm, can you please send me the log so i can take a quick look?

**Comment by mtkarimi** [comment]
You need to set the Qt attributes before creating the QCoreApplication instance. Additionally, the error indicates that the connection to the server at `127.0.0.1:8001` is being refused, suggesting that the server might not be running or is not accessible. Here's a corrected version of your script with the Qt attributes set early and with added error handling:

```python
import sys
import requests
from PyQt5.QtCore import QCoreApplication, Qt

# Set Qt attributes before creating the QCoreApplication instance
QCoreApplication.setAttribute(Qt.AA_UseSoftwareOpenGL)
QCoreApplication.setAttribute(Qt.AA_ShareOpenGLContexts)

# Your other imports and code
# ...

def send_data_to_carvann(carvann_data):
    CARVANN_URL = 'http://127.0.0.1:8001/api/v1/camera/'
    json_data = {}  # your json_data here
    files = {}  # your files here
    try:
        response = requests.post(CARVANN_URL, data=json_data, files=files)
        response.raise_for_status()  # Raise an HTTPError for bad responses (4xx and 5xx)
    except requests.exceptions.ConnectionError as e:
        print(f"Error: Could not connect to {CARVANN_URL}.")
    except requests.exceptions.HTTPError as e:
        print(f"HTTP error occurred: {e}")
    except requests.exceptions.RequestException as e:
        print(f"An error occurred: {e}")

# Your other functions and code
# ...

if __name__ == "__main__":
    app = QCoreApplication(sys.argv)
    # Your main code here
    sys.exit(app.exec_())
```

Make sure your server at `127.0.0.1:8001` is running and accessible before you try to connect to it. This should help in resolving the connection errors and setting the Qt attributes correctly.

**Comment by mohsenkondori** [comment]
Memory usage is very high, how can I decrease it? @mtkarimi @mohammadhssn
