### ISSUE TITLE
dealing-with-dependency-conflicts

### ISSUE THREAD

**Issue by maysam** [mtkarimi/persian-license-plate-recognition#6]
ERROR: Cannot install -r requirements.txt (line 5) and urllib3==2.0.7 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested urllib3==2.0.7
    botocore 1.34.45 depends on urllib3<1.27 and >=1.25.4; python_version < "3.10"

**Comment by mtkarimi** [comment]
i updated to core, please clone and let me know

**Comment by aminallahrabi** [comment]
i have some conflict package version, 
so i install them lonely : pip install keras ......
then change the requirements.txt file . go to file and change the version of package .
after install , you can upgrade them.
