### ISSUE TITLE
error to install "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by tamiji002** [mtkarimi/persian-license-plate-recognition#7]
ERROR: Could not find a version that satisfies the requirement tensorflow-macos==2.15.0 (from versions: none)
ERROR: No matching distribution found for tensorflow-macos==2.15.0

ubuntu 22.04 LTS

![11](https://github.com/mtkarimi/smart-resident-guard/assets/160832184/f33b8371-9766-4a23-a674-7174a2cc5caa)

**Comment by mtkarimi** [comment]
i updated to core, please clone and let me know
