### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by Behzad-AB** [mtkarimi/persian-license-plate-recognition#8]
Hi,
I'm getting "ModuleNotFoundError" for 2 modules of 'distutils' and 'torch', while attempting to run the application.

Keep up the excellent work!
much appreciated

**Comment by mtkarimi** [comment]
i updated to core, please clone and let me know

**Comment by aminallahrabi** [comment]
you can install them with pip instal tourch instead of using requirments.txt file.
