### ISSUE TITLE
can't open file 'C:\\New folder\\home-yolo.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by EHSANIprogramer** [mtkarimi/persian-license-plate-recognition#9]
hi . please Hello, please help me in this matter
when i comanded this code ->  python home-yolo.py  (recived this->)   can't open file 'C:\\New folder\\home-yolo.py': [Errno 2] No such file or directory

![error](https://github.com/mtkarimi/smart-resident-guard/assets/113135686/0d73e300-0355-4a70-826e-ce960fcc2c31)

**Comment by mtkarimi** [comment]
i updated to core, please clone and let me know
